apiVersion: app.kiegroup.org/v2
kind: KieApp
metadata:
  name: workshop
spec:
  truststore:
    openshiftCaBundle: true
  commonConfig:
    adminPassword: admin
    adminUser: admin
  environment: rhpam-production-immutable
  objects:
    servers:
      - env:
          - name: MAVEN_REPO_URL
            value: >-
              http://nexusrepo-sonatype-nexus-service-labs-infra.apps.cluster-6j7kf.6j7kf.sandbox175.opentlc.com/repository/maven-public/
          - name: MAVEN_MIRROR_URL
            value: >-
              http://nexusrepo-sonatype-nexus-service-labs-infra.apps.cluster-6j7kf.6j7kf.sandbox175.opentlc.com/repository/maven-public/
          - name: KIE_SERVER_CONTAINER_DEPLOYMENT
            value: 'introduction_dmn=com.myspace:Introduction_DMN:1.0.0'
          - name: PROMETHEUS_SERVER_EXT_DISABLED
            value: 'false'
        deployments: 1
        database:
          type: h2
        replicas: 1
